### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by ckirksey3** [voxable-labs/actions-on-google-api-ai-boilerplate#1]
Thanks for sharing this! I'd like to use it, but I'm a little nervous about the lack of license. Would you mind adding one, perhaps the MIT? https://choosealicense.com/

**Comment by techpeace** [comment]
All set! I had to go with Apache, as that was the license used on the project I originally based this on. I also added a button for remixing the project on Glitch. Thanks for catching that!

**Comment by ckirksey3** [comment]
Thanks for the quick reply! Yeah, I've noticed all boilerplate projects for Actions have Apache since Google used it for their example. I may try building my own from scratch and giving it a super unrestrictive license.
